// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(MyosotisDbContext))]
    [Migration("20260921200309_AddMirrorDungeonSave")]
    partial class AddMirrorDungeonSave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Database.Entities.AnnouncerPreset", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_id");

                    b.HasKey("Uid", "PresetId")
                        .HasName("pk_announcer_presets");

                    b.ToTable("announcer_presets", (string)null);
                });

            modelBuilder.Entity("Database.Entities.AnnouncerPresetEntry", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preset_id");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("AnnouncerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("announcer_id");

                    b.HasKey("Uid", "PresetId", "Idx")
                        .HasName("pk_announcer_preset_entries");

                    b.ToTable("announcer_preset_entries", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Formation", b =>
                {
                    b.Property<long>("FormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("formation_id");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.HasKey("FormationId")
                        .HasName("pk_formations");

                    b.HasIndex("Uid", "Id")
                        .IsUnique()
                        .HasDatabaseName("ix_formations_uid_id");

                    b.ToTable("formations", (string)null);
                });

            modelBuilder.Entity("Database.Entities.FormationDetail", b =>
                {
                    b.Property<long>("FormationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("formation_id");

                    b.Property<int>("PersonalityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("personality_id");

                    b.Property<bool>("IsParticipated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_participated");

                    b.Property<int>("ParticipationOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("participation_order");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skin_id");

                    b.HasKey("FormationId", "PersonalityId")
                        .HasName("pk_formation_details");

                    b.ToTable("formation_details", (string)null);
                });

            modelBuilder.Entity("Database.Entities.FormationEgo", b =>
                {
                    b.Property<long>("FormationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("formation_id");

                    b.Property<int>("PersonalityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("personality_id");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("EgoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ego_id");

                    b.HasKey("FormationId", "PersonalityId", "Idx")
                        .HasName("pk_formation_egos");

                    b.ToTable("formation_egos", (string)null);
                });

            modelBuilder.Entity("Database.Entities.FormationName", b =>
                {
                    b.Property<long>("FormationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("formation_id");

                    b.Property<int>("K")
                        .HasColumnType("INTEGER")
                        .HasColumnName("k");

                    b.Property<int>("V")
                        .HasColumnType("INTEGER")
                        .HasColumnName("v");

                    b.HasKey("FormationId", "K")
                        .HasName("pk_formation_names");

                    b.ToTable("formation_names", (string)null);
                });

            modelBuilder.Entity("Database.Entities.MirrorDungeonSave", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dungeon_id");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("IsEnded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ended");

                    b.Property<string>("SaveJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("save_json");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Uid")
                        .HasName("pk_mirror_dungeon_saves");

                    b.ToTable("mirror_dungeon_saves", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProfileBanner", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.Property<int>("Value2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value2");

                    b.Property<int>("Value3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value3");

                    b.Property<int>("Value4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value4");

                    b.Property<int>("Value5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value5");

                    b.HasKey("Uid", "Id")
                        .HasName("pk_profile_banners");

                    b.ToTable("profile_banners", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProfileSupportEgo", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("EgoIdx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ego_idx");

                    b.Property<int>("G")
                        .HasColumnType("INTEGER")
                        .HasColumnName("g");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.HasKey("Uid", "Idx", "EgoIdx")
                        .HasName("pk_profile_support_egos");

                    b.ToTable("profile_support_egos", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProfileSupportPersonality", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("Gi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gi");

                    b.Property<int>("Gl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gl");

                    b.Property<int>("L")
                        .HasColumnType("INTEGER")
                        .HasColumnName("l");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pid");

                    b.Property<int>("Sid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sid");

                    b.HasKey("Uid", "Idx")
                        .HasName("pk_profile_support_personalities");

                    b.ToTable("profile_support_personalities", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProfileTicket", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<string>("TicketType")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_type");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER")
                        .HasColumnName("date");

                    b.HasKey("Uid", "TicketType", "Id")
                        .HasName("pk_profile_tickets");

                    b.ToTable("profile_tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_profile_tickets_ticket_type", "ticket_type IN ('LEFT','RIGHT','EGOBG')");
                        });
                });

            modelBuilder.Entity("Database.Entities.RailwaySave", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dungeon_id");

                    b.Property<int>("CurrentClearRotation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_clear_rotation");

                    b.Property<int>("CurrentNode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_node");

                    b.Property<int>("CurrentSeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_seed");

                    b.Property<long>("FirstClearDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_clear_date");

                    b.Property<int>("InitSeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("init_seed");

                    b.Property<int>("LastClearNode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_clear_node");

                    b.Property<int>("LastClearRotation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_clear_rotation");

                    b.Property<int>("LastEnterNodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_enter_node_id");

                    b.Property<int>("PayReward")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pay_reward");

                    b.Property<int>("PrevClearNode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prev_clear_node");

                    b.Property<int>("RewardState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reward_state");

                    b.HasKey("Uid", "DungeonId")
                        .HasName("pk_railway_saves");

                    b.ToTable("railway_saves", (string)null);
                });

            modelBuilder.Entity("Database.Entities.RailwaySaveUnit", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dungeon_id");

                    b.Property<int>("Pord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pord");

                    b.Property<int>("G")
                        .HasColumnType("INTEGER")
                        .HasColumnName("g");

                    b.Property<int>("Gi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gi");

                    b.Property<int>("L")
                        .HasColumnType("INTEGER")
                        .HasColumnName("l");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pid");

                    b.Property<int>("Sid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sid");

                    b.Property<int>("Sp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sp");

                    b.HasKey("Uid", "DungeonId", "Pord")
                        .HasName("pk_railway_save_units");

                    b.ToTable("railway_save_units", (string)null);
                });

            modelBuilder.Entity("Database.Entities.RailwaySaveUnitEgo", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dungeon_id");

                    b.Property<int>("Pord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pord");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<int>("EgoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ego_id");

                    b.Property<int>("Gacksung")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gacksung");

                    b.HasKey("Uid", "DungeonId", "Pord", "Idx")
                        .HasName("pk_railway_save_unit_egos");

                    b.ToTable("railway_save_unit_egos", (string)null);
                });

            modelBuilder.Entity("Database.Entities.User", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_type");

                    b.Property<string>("Credential")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("credential");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp");

                    b.Property<long>("LastLoginAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_login_at");

                    b.Property<long>("LastStaminaRecover")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_stamina_recover");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<long>("RegisterDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("register_date");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stamina");

                    b.HasKey("Uid")
                        .HasName("pk_users");

                    b.HasIndex("Credential")
                        .IsUnique()
                        .HasDatabaseName("ix_users_credential");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserAnnouncer", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("AnnouncerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("announcer_id");

                    b.HasKey("Uid", "AnnouncerId")
                        .HasName("pk_user_announcers");

                    b.ToTable("user_announcers", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserAnnouncerState", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("CurPresetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cur_preset_id");

                    b.HasKey("Uid")
                        .HasName("pk_user_announcer_state");

                    b.ToTable("user_announcer_state", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserBanner", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Acquiretime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquiretime");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.Property<int>("Value2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value2");

                    b.Property<int>("Value3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value3");

                    b.Property<int>("Value4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value4");

                    b.Property<int>("Value5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value5");

                    b.HasKey("Uid", "Id")
                        .HasName("pk_user_banners");

                    b.ToTable("user_banners", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserEgo", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("EgoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ego_id");

                    b.Property<long>("AcquireTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquire_time");

                    b.Property<int>("Gacksung")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gacksung");

                    b.HasKey("Uid", "EgoId")
                        .HasName("pk_user_egos");

                    b.ToTable("user_egos", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserItem", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER")
                        .HasColumnName("num");

                    b.HasKey("Uid", "ItemId")
                        .HasName("pk_user_items");

                    b.ToTable("user_items", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserPersonality", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("PersonalityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("personality_id");

                    b.Property<long>("AcquireTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquire_time");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exp");

                    b.Property<int>("Gacksung")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gacksung");

                    b.Property<int>("GacksungIllustType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gacksung_illust_type");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.HasKey("Uid", "PersonalityId")
                        .HasName("pk_user_personalities");

                    b.ToTable("user_personalities", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UserProfile", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<long?>("Date")
                        .HasColumnType("INTEGER")
                        .HasColumnName("date");

                    b.Property<int?>("EgoBackgroundId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ego_background_id");

                    b.Property<int?>("IllustGacksungLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("illust_gacksung_level");

                    b.Property<int?>("IllustId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("illust_id");

                    b.Property<int?>("LeftBorderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("left_border_id");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("PublicUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_uid");

                    b.Property<int?>("RightBorderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("right_border_id");

                    b.Property<int?>("SentenceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sentence_id");

                    b.Property<int?>("WordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("word_id");

                    b.HasKey("Uid")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Database.Entities.AnnouncerPreset", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_announcer_presets_users_uid");
                });

            modelBuilder.Entity("Database.Entities.AnnouncerPresetEntry", b =>
                {
                    b.HasOne("Database.Entities.AnnouncerPreset", null)
                        .WithMany()
                        .HasForeignKey("Uid", "PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_announcer_preset_entries_announcer_presets_uid_preset_id");
                });

            modelBuilder.Entity("Database.Entities.Formation", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_formations_users_uid");
                });

            modelBuilder.Entity("Database.Entities.FormationDetail", b =>
                {
                    b.HasOne("Database.Entities.Formation", null)
                        .WithMany()
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_formation_details_formations_formation_id");
                });

            modelBuilder.Entity("Database.Entities.FormationEgo", b =>
                {
                    b.HasOne("Database.Entities.FormationDetail", null)
                        .WithMany()
                        .HasForeignKey("FormationId", "PersonalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_formation_egos_formation_details_formation_id_personality_id");
                });

            modelBuilder.Entity("Database.Entities.FormationName", b =>
                {
                    b.HasOne("Database.Entities.Formation", null)
                        .WithMany()
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_formation_names_formations_formation_id");
                });

            modelBuilder.Entity("Database.Entities.MirrorDungeonSave", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mirror_dungeon_saves_users_uid");
                });

            modelBuilder.Entity("Database.Entities.ProfileBanner", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_banners_users_uid");
                });

            modelBuilder.Entity("Database.Entities.ProfileSupportEgo", b =>
                {
                    b.HasOne("Database.Entities.ProfileSupportPersonality", null)
                        .WithMany()
                        .HasForeignKey("Uid", "Idx")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_support_egos_profile_support_personalities_uid_idx");
                });

            modelBuilder.Entity("Database.Entities.ProfileSupportPersonality", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_support_personalities_users_uid");
                });

            modelBuilder.Entity("Database.Entities.ProfileTicket", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_tickets_users_uid");
                });

            modelBuilder.Entity("Database.Entities.RailwaySave", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_railway_saves_users_uid");
                });

            modelBuilder.Entity("Database.Entities.RailwaySaveUnit", b =>
                {
                    b.HasOne("Database.Entities.RailwaySave", null)
                        .WithMany()
                        .HasForeignKey("Uid", "DungeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_railway_save_units_railway_saves_uid_dungeon_id");
                });

            modelBuilder.Entity("Database.Entities.RailwaySaveUnitEgo", b =>
                {
                    b.HasOne("Database.Entities.RailwaySaveUnit", null)
                        .WithMany()
                        .HasForeignKey("Uid", "DungeonId", "Pord")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_railway_save_unit_egos_railway_save_units_uid_dungeon_id_pord");
                });

            modelBuilder.Entity("Database.Entities.UserAnnouncer", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_announcers_users_uid");
                });

            modelBuilder.Entity("Database.Entities.UserAnnouncerState", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_announcer_state_users_uid");
                });

            modelBuilder.Entity("Database.Entities.UserBanner", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_banners_users_uid");
                });

            modelBuilder.Entity("Database.Entities.UserEgo", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_egos_users_uid");
                });

            modelBuilder.Entity("Database.Entities.UserItem", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_items_users_uid");
                });

            modelBuilder.Entity("Database.Entities.UserPersonality", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_personalities_users_uid");
                });

            modelBuilder.Entity("Database.Entities.UserProfile", b =>
                {
                    b.HasOne("Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_uid");
                });
#pragma warning restore 612, 618
        }
    }
}
